// ZeroClaw Rust 源码中文标签 — Web 端自动替换（不改 Rust 源码）
// 每行: 英文原文 → 中文译文

const ZH_RUST_LABELS: Record<string, string> = {
  // ═══ 工具名 ═══
  'Shell': '终端',
  'File System': '文件系统',
  'Weather': '天气',
  'Spawn SubAgent': '启动子智能体',
  'shell': '终端',
  'file_read': '读文件',
  'file_write': '写文件',
  'file_edit': '编辑文件',
  'file_download': '下载文件',
  'file_upload': '上传文件',
  'file_upload_bundle': '文件上传集',
  'filesystem': '文件系统',
  'glob_search': 'glob搜索',
  'content_search': '内容搜索',
  'browser': '浏览器',
  'browser_open': '打开浏览器',
  'browser_delegate': '浏览器代理',
  'web_fetch': '网页抓取',
  'web_search_tool': '网页搜索',
  'screenshot': '截图',
  'canvas': '画布',
  'workspace': '工作区',
  'sandbox_exec': '沙箱执行',
  'backup': '备份',
  'schedule': '计划任务',
  'calculator': '计算器',
  'datetime': '日期时间',
  'weather_tool': '天气',
  'text_browser': '文本浏览器',
  'http_request': 'HTTP请求',
  'proxy_config': '代理配置',

  // ═══ Cron 工具 ═══
  'cron_add': '添加定时任务',
  'cron_list': '列出定时任务',
  'cron_remove': '删除定时任务',
  'cron_update': '更新定时任务',
  'cron_run': '运行定时任务',
  'cron_runs': '定时任务历史',

  // ═══ 记忆工具 ═══
  'memory_store': '存储记忆',
  'memory_recall': '召回记忆',
  'memory_forget': '遗忘记忆',
  'memory_export': '导出记忆',
  'memory_purge': '清理记忆',

  // ═══ SOP 工具 ═══
  'sop_execute': '执行SOP',
  'sop_list': '列出SOP',
  'sop_status': 'SOP状态',
  'sop_advance': '推进SOP',
  'sop_approve': '审批SOP',
  'sop_workshop': 'SOP编辑器',

  // ═══ 技能工具 ═══
  'skill_manage': '管理技能',
  'skill_view': '查看技能',
  'skill_tool': '技能工具',
  'skill_http': '技能HTTP',
  'skills_list': '技能列表',
  'read_skill': '读技能',

  // ═══ 智能体/委派 ═══
  'spawn_subagent': '创建子智能体',
  'send_message_to_peer': '发送同伴消息',
  'model_routing_config': '模型路由配置',
  'model_switch_trigger': '模型切换触发',
  'child_model_switch': '子模型切换',
  'delegate': '委派',

  // ═══ 安全 ═══
  'security_ops': '安全操作',
  'safety': '安全检查',
  'ask_user': '询问用户',
  'escalate_to_human': '转人工',
  'tool_honesty': '工具诚实度',

  // ═══ 硬件 ═══
  'gpio_read': 'GPIO读',
  'gpio_write': 'GPIO写',
  'gpio_rpi_blink': '树莓派闪烁',
  'gpio_rpi_read': '树莓派读',
  'gpio_rpi_write': '树莓派写',
  'i2c_read': 'I2C读',
  'i2c_scan': 'I2C扫描',
  'i2c_write': 'I2C写',
  'spi_transfer': 'SPI传输',
  'device_exec': '设备执行',
  'device_read_code': '读设备代码',
  'device_write_code': '写设备代码',
  'read_device': '读设备',
  'set_device': '设置设备',
  'hardware_board_info': '板卡信息',
  'hardware_capabilities': '硬件能力',
  'hardware_memory_map': '内存映射',
  'hardware_memory_read': '内存读取',
  'rpi_system_info': '树莓派系统',
  'pico_flash': 'Pico烧录',
  'arduino_upload': 'Arduino上传',

  // ═══ 语音 ═══
  'voice_call': '语音通话',
  'voice_wake': '语音唤醒',
  'speak': '朗读',
  'listen': '监听',
  'sense': '传感',

  // ═══ 图片 ═══
  'image_gen': '图片生成',
  'image_info': '图片信息',
  'Image generation': '图片生成',

  // ═══ 会话 ═══
  'sessions_current': '当前会话',
  'sessions_delete': '删除会话',
  'sessions_history': '会话历史',
  'sessions_list': '会话列表',
  'sessions_reset': '重置会话',
  'sessions_send': '发送会话',

  // ═══ 数据管理 ═══
  'data_management': '数据管理',
  'datasheet': '数据表',
  'recording': '录制',
  'event_capture': '事件捕获',
  'report_template': '报告模板',
  'project_intel': '项目情报',

  // ═══ 网络 ═══
  'cloud_ops': '云端操作',
  'cloudflare': 'Cloudflare',
  'cloud_patterns': '云端模式',
  'ngrok': 'Ngrok',
  'tailscale': 'Tailscale',
  'openvpn': 'OpenVPN',
  'bubblewrap': '沙箱',
  'firejail': 'Firejail',
  'landlock': 'Landlock',

  // ═══ 频道 ═══
  'discord': 'Discord',
  'telegram': 'Telegram',
  'slack': 'Slack',
  'wechat': '微信',
  'whatsapp': 'WhatsApp',
  'signal': 'Signal',
  'matrix': 'Matrix',
  'irc': 'IRC',
  'bluesky': 'Bluesky',
  'twitter': 'X/Twitter',
  'reddit': 'Reddit',
  'nostr': 'Nostr',
  'line': 'Line',
  'dingtalk': '钉钉',
  'feishu': '飞书',
  'twitch': 'Twitch',
  'mattermost': 'Mattermost',
  'nextcloud_talk': 'Nextcloud Talk',
  'mochat': 'MoChat',
  'wecom': '企业微信',
  'wecom_ws': '企业微信WS',
  'wati': 'WATI',
  'imessage': 'iMessage',
  'linkedin': 'LinkedIn',
  'linq': 'Linq',
  'discord_search': 'Discord搜索',
  'gmail_push': 'Gmail推送',
  'email': '邮件',
  'email_read': '读邮件',
  'email_search': '搜邮件',
  'webhook': 'Webhook',
  'broadcast': '广播',

  // ═══ 代码工具 ═══
  'codex_cli': 'Codex CLI',
  'gemini_cli': 'Gemini CLI',
  'opencode_cli': 'OpenCode CLI',
  'claude_code': 'Claude Code',
  'claude_code_runner': 'Claude Code Runner',
  'rust': 'Rust',
  'wasm': 'WASM',
  'runtime': '运行时',

  // ═══ 集成 ═══
  'google': 'Google',
  'google_workspace': 'Google Workspace',
  'microsoft365': 'Microsoft 365',
  'composio': 'Composio插件',
  'knowledge': '知识库',
  'docker': 'Docker',
  'postgres': 'PostgreSQL',
  'sqlite': 'SQLite',
  'qdrant': 'Qdrant',
  'prometheus': 'Prometheus',
  'otel': 'OpenTelemetry',
  'lucid': 'Lucid',
  'markdown': 'Markdown',
  'git': 'Git',
  'git_forge': 'Git Forge',
  'github': 'GitHub',
  'gitea': 'Gitea',
  'jira': 'Jira',
  'notion': 'Notion',

  // ═══ 配置菜单标签 ═══
  'Model providers': '模型提供商',
  'Model routes': '模型路由',
  'Embedding routes': '嵌入路由',
  'Risk profiles': '风险配置',
  'Runtime profiles': '运行时配置',
  'TTs providers': '语音合成',
  'TTS providers': '语音合成',
  'Transcription providers': '语音识别',
  'Skill bundles': '技能集',
  'Knowledge bundles': '知识库集',
  'MCP servers': 'MCP 服务器',
  'MCP bundles': 'MCP 服务集',
  'Peer groups': '同伴组',
  'Onboard state': '首次设置',
  'Conversational ai': '对话 AI',
  'Data retention': '数据保留',
  'Unattended upgrades': '自动升级',
  'File download': '文件下载',
  'File upload': '文件上传',
  'File upload bundle': '文件上传集',
  'Query classification': '查询分类',
  'Cloud ops': '云端运维',
  'Cost ops': '费用控制',
  'Companion network peers': '同伴网络节点',
  'Microsoft 365': 'Microsoft 365',

  // ═══ 分组标签 ═══
  'Foundation': '基础',
  'Agent': '智能体',
  'Multi-agent': '多智能体',
  'Tools': '工具',
  'Integrations': '集成',
  'Network': '网络',
  'Storage': '存储',
  'Operations': '运维',
  'MultiAgent': '多智能体',
  'ToolsAutomation': '工具与自动化',
  'ChatPlatform': '聊天平台',
  'AIModel': 'AI 模型',
  'PlatformService': '平台服务',
  'FileTransfer': '文件传输',

  // ═══ 通用字段标签 ═══
  'Enabled': '已启用',
  'Disabled': '已禁用',
  'enabled': '已启用',
  'disabled': '已禁用',
  'Bind': '绑定',
  'Port': '端口',
  'Host': '主机',
  'URI': '地址',
  'URL': 'URL',
  'Path': '路径',
  'Key': '密钥',
  'Secret': '密钥',
  'Token': '令牌',
  'Name': '名称',
  'Alias': '别名',
  'Tags': '标签',
  'Type': '类型',
  'Status': '状态',
  'Mode': '模式',
  'Scope': '范围',
  'Format': '格式',
  'Encoding': '编码',
  'Target': '目标',
  'Source': '来源',
  'Timeout': '超时',
  'Interval': '间隔',
  'Limit': '限制',
  'Threshold': '阈值',
  'Label': '标签',
  'Title': '标题',
  'Body': '正文',
  'Subject': '主题',
  'From': '发件人',
  'To': '收件人',
  'Content': '内容',
  'Message': '消息',
  'Error': '错误',
  'Warning': '警告',
  'Info': '提示',
  'Success': '成功',
  'Failed': '失败',
  'Failure': '失败',
  'State': '状态',
  'Status': '状态',
  'Mode': '模式',
  'Version': '版本',
  'Description': '描述',
  'Summary': '摘要',
  'Details': '详情',
  'Options': '选项',
  'Actions': '操作',
  'Action': '动作',
  'Step': '步骤',
  'Steps': '步骤',
  'Query': '查询',
  'Command': '命令',
  'Trigger': '触发器',
  'Triggers': '触发器',
  'Rules': '规则',
  'Permissions': '权限',
  'Visibility': '可见性',
  'Language': '语言',
  'Locale': '区域',
  'Currency': '货币',
  'Rate': '速率',
  'Cost': '费用',
  'Total': '总计',
  'Used': '已用',
  'Free': '空闲',
  'Capacity': '容量',
  'Size': '大小',
  'Distance': '距离',
  'Duration': '持续时间',
  'Role': '角色',
  'Team': '团队',
  'User': '用户',
  'Owner': '所有者',
  'Public': '公开',
  'Private': '私有',
  'Internal': '内部',
  'Public Base URL': '公共 URL',
  'Base URL': '基础 URL',
  'API Key': 'API 密钥',
  'API URL': 'API 地址',
  'Model ID': '模型 ID',
  'Model Name': '模型名',
  'Provider': '提供商',
  'Endpoint': '端点',
  'Endpoint URL': '端点地址',
  'Context Path': '上下文路径',
  'Request Timeout': '请求超时',
  'Read Timeout': '读取超时',
  'Write Timeout': '写入超时',
  'Auto Ack': '自动确认',
  'Loop Guard': '循环防护',
  'Default': '默认',
  'Custom': '自定义',
  'Allow': '允许',
  'Deny': '拒绝',
  'Block': '阻止',
  'Read': '读',
  'Write': '写',
  'Send': '发送',
  'Receive': '接收',
  'Delete': '删除',
  'Create': '创建',
  'Update': '更新',
  'Export': '导出',
  'Import': '导入',
  'Upload': '上传',
  'Download': '下载',
  'Search': '搜索',
  'Filter': '筛选',
  'Sort': '排序',
  'Save': '保存',
  'Cancel': '取消',
  'Confirm': '确认',
  'Submit': '提交',
  'Reset': '重置',
  'Clear': '清除',
  'Refresh': '刷新',
  'Reload': '重载',
  'Loading': '加载中',
  'Saving': '保存中',
  'Deleting': '删除中',
  'Creating': '创建中',
  'Updating': '更新中',
  'Processing': '处理中',
  'Connecting': '连接中',
  'Connected': '已连接',
  'Disconnected': '已断开',
  'Running': '运行中',
  'Stopped': '已停止',
  'Paused': '已暂停',
  'Active': '活跃',
  'Inactive': '不活跃',
  'Online': '在线',
  'Offline': '离线',
  'Available': '可用',
  'Unavailable': '不可用',
  'Supported': '支持',
  'Unsupported': '不支持',
  'Required': '必填',
  'Optional': '可选',
  'Valid': '有效',
  'Invalid': '无效',
  'Expired': '已过期',
  'Pending': '待处理',
  'Approved': '已批准',
  'Rejected': '已拒绝',
  'Verified': '已验证',
  'Protected': '受保护',
  'Restricted': '受限制',
  'Configured': '已配置',
  'Unconfigured': '未配置',
  'Channels': '频道',
  'Memory': '记忆',
  'Skills': '技能',
  'Agents': '智能体',
  'Cron': '定时任务',
  'Tunnel': '隧道',
  'Hardware': '硬件',
  'Backup': '备份',
  'Heartbeat': '心跳',
  'Hooks': '钩子',
  'Pipeline': '管线',
  'Pacing': '限速',
  'Observability': '可观测性',
  'Escalation': '升级通知',
  'Trust': '信任',
  'Eval': '评估',
  'Cost': '费用',
  'Runtime': '运行时',
  'Gateway': '网关',
  'Identity': '身份',
  'Identity Capture': '身份捕获',
  'Sandbox': '沙箱',
  'Browser': '浏览器',
  'Browser Delegate': '浏览器代理',
  'Templates': '模板',
  'Template': '模板',
  'Extensions': '扩展',
  'Plugins': '插件',
  'Modules': '模块',
  'Libraries': '库',
  'Deployments': '部署',
  'Releases': '发布',
  'Presets': '预设',
  'Configurations': '配置',
  'Workflows': '工作流',
  'Tasks': '任务',
  'Jobs': '作业',
  'Events': '事件',
  'Metrics': '指标',
  'Logs': '日志',
  'Traces': '追踪',
  'Profiles': '配置',
  'Peers': '同伴',
  'Sessions': '会话',
  'Files': '文件',
  'Directories': '目录',
  'Bundles': '集',
  'Subscriptions': '订阅',
  'Notifications': '通知',
  'Schedule': '计划',
  'Frequency': '频率',
  'Priority': '优先级',
  'Weight': '权重',
  'Score': '分数',
  'Level': '级别',
  'Count': '数量',
  'Index': '索引',
  'ID': 'ID',
  'UID': 'UID',
  'UUID': 'UUID',
  'MD5': 'MD5',
  'SHA256': 'SHA256',
  'Provider': '提供商',
  'Channel': '频道',
  'Server': '服务器',
  'Client': '客户端',
  'Bucket': '桶',
  'Collection': '集合',
  'Table': '表',
  'Row': '行',
  'Column': '列',
  'Page': '页',
  'Image': '图片',
  'Video': '视频',
  'Audio': '音频',
  'Text': '文本',
  'Code': '代码',
  'HTML': 'HTML',
  'CSS': 'CSS',
  'JSON': 'JSON',
  'YAML': 'YAML',
  'TOML': 'TOML',
  'Markdown': 'Markdown',
  'XML': 'XML',
  'CSV': 'CSV',
  'SQL': 'SQL',
  'GraphQL': 'GraphQL',
  'REST': 'REST',
  'gRPC': 'gRPC',
  'TCP': 'TCP',
  'UDP': 'UDP',
  'HTTP': 'HTTP',
  'HTTPS': 'HTTPS',
  'TLS': 'TLS',
  'SSL': 'SSL',
  'DNS': 'DNS',
  'IP': 'IP',
  'MAC': 'MAC',
  'VRF': 'VRF',
  'VLAN': 'VLAN',
  'VPN': 'VPN',
  'OS': '操作系统',
  'Process': '进程',
  'Thread': '线程',
  'CPU': 'CPU',
  'GPU': 'GPU',
  'RAM': '内存',
  'RAM Memory': '内存',
  'Disk': '磁盘',
  'Network': '网络',
  'Firewall': '防火墙',
  'Proxy': '代理',
  'Cache': '缓存',
  'Queue': '队列',
  'Batch': '批次',
  'Stream': '流',
  'WebSocket': 'WebSocket',
  'Webhook': 'Webhook',
  'API': 'API',
  'SDK': 'SDK',
  'CLI': 'CLI',
  'TUI': 'TUI',
  'GUI': 'GUI',
  'Daemon': '守护进程',
  'Service': '服务',
  'Engine': '引擎',
  'Framework': '框架',
  'Platform': '平台',
  'Runtime': '运行时',
  'Environment': '环境',
  'Context': '上下文',
  'Locale': '区域设置',
  'Region': '地区',
  'Zone': '区域',
  'Tenant': '租户',
  'Room': '房间',
  'Workspace': '工作区',
  'Dashboard': '仪表盘',
  'Panel': '面板',
  'Sidebar': '侧边栏',
  'Header': '顶栏',
  'Footer': '页脚',
  'Menu': '菜单',
  'Tab': '标签页',
  'Section': '分区',
  'Category': '分类',
  'Group': '分组',
  'List': '列表',
  'Grid': '网格',
  'Table': '表格',
  'Chart': '图表',
  'Map': '地图',
  'Canvas': '画布',
  'Overlay': '浮层',
  'Popup': '弹窗',
  'Modal': '弹窗',
  'Dialog': '对话框',
  'Drawer': '抽屉',
  'Toast': '通知',
  'Alert': '警报',
  'Badge': '徽章',
  'Tag': '标签',
  'Chip': '标记',
  'Pill': '药丸',
  'Dot': '圆点',
  'Icon': '图标',
  'Avatar': '头像',
  'Logo': 'Logo',
  'Banner': '横幅',
  'Card': '卡片',
  'Button': '按钮',
  'Link': '链接',
  'Input': '输入框',
  'Textarea': '文本框',
  'Select': '下拉框',
  'Checkbox': '复选框',
  'Radio': '单选框',
  'Switch': '开关',
  'Slider': '滑块',
  'Toggle': '切换',
  'Dropdown': '下拉菜单',
  'Tooltip': '提示框',
  'Popover': '弹出框',
  'Toolbar': '工具栏',
  'Status Bar': '状态栏',
  'Progress Bar': '进度条',
  'Spinner': '加载图标',
  'Skeleton': '骨架屏',
  'Placeholder': '占位符',
  'Empty': '空',
  'None': '无',
  'Null': '空',
  'Undefined': '未定义',
  'Unknown': '未知',
  'Missing': '缺失',
  'Added': '已添加',
  'Removed': '已移除',
  'Changed': '已更改',
  'Modified': '已修改',
  'Deleted': '已删除',
  'Created': '已创建',
  'Updated': '已更新',
  'Refreshed': '已刷新',
  'Reloaded': '已重载',
  'Restarted': '已重启',
  'Started': '已启动',
  'Stopped': '已停止',
  'Cancelled': '已取消',
  'Skipped': '已跳过',
  'Completed': '已完成',
  'Finished': '已完成',
  'Ended': '已结束',
  'Dropped': '已丢弃',
  'Ignored': '已忽略',
  'Saved': '已保存',
  'Restored': '已恢复',
  'Exported': '已导出',
  'Downloaded': '已下载',
  'Uploaded': '已上传',
};

export default ZH_RUST_LABELS;
